Preserve data
ghermaico135/Portfolio pull request #13
Opened 2023-04-20 18:06 UTC by ghermaico135

2023-04-20 19:00 UTC, Favourezeugwa reviewed
Hi team 👋🏽,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌❌❌

You have submitted a project, that does not include a descriptive Pull request summary.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-20 19:46 UTC, ghermaico135 commented
Preserve Code to localstorage-is after submitting the data it stored on the web browser lcoalstorage.So this code set and get items to localstorage on the browser.

2023-04-20 20:02 UTC, LionRouge1 requested changes
Hi @ghermaico135, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

## Highlights
- Good PR :heavy_check_mark: 
- Good commit :+1: 
- All linters passed :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 20:02 UTC, LionRouge1 commented on js/preserveData.js
> +});
- [ ] Great job preserving the data in the browser :clap: :sunglasses: However data should be saved in the browser when the user changes the content of any input field. But you're saving the data when the user clicks on the button submit, Kindly check it

2023-04-21 07:51 UTC, ghermaico135 commented
Changing the event handler to save on submit rather than on click

2023-04-21 08:36 UTC, divinecharlotte requested changes
Hi @Team , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive PR ✔️ 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 08:36 UTC, divinecharlotte commented on js/preserveData.js
> +});
- [ ] As requested by the previous reviewer kindly consider hitting the below  points as they are requirements 
-  When the user changes the content of any input field, the data is saved to the local storage.
- When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.

 ☠️  Do not create one local storage entry per input field. just create one local storage and as long as the user updates one field the whole local storage gets updated


doing the above will make your project stand out and fulfill all the requirements

2023-04-21 08:51 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi Team
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 08:51 UTC, joel-kalema commented on js/preserveData.js
> +});
- [ ] Good job @ghermaico135 😃 , as the [previous reviewer](https://github.com/ghermaico135/Portfolio/pull/13#:~:text=However%20data%20should%20be%20saved%20in%20the%20browser%20when%20the%20user%20changes%20the%20content%20of%20any%20input%20field.%20But%20you%27re%20saving%20the%20data%20when%20the%20user%20clicks%20on%20the%20button%20submit%2C%20Kindly%20check%20it) said,  data should be saved in the browser when the user changes the content of any input field. But you're saving the data when the user clicks on the button submit, which means that the data will be saved when the user will be changing the content of any input field, not only when he clicks on the button submit. Kindly check it 👍

2023-04-21 08:53 UTC, ghermaico135 commented
I Added "change eventlistner" which captures the change on localstorage when users input to the field automatically

2023-04-21 08:59 UTC, amejid approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing ✔️ 
- Correct use of Github flow ✔️ 
- Data getting preserved in local storage ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 09:06 UTC, joel-kalema commented
> I Added "change eventlistner" which captures the change on localstorage when users input to the field automatically

Hello @ghermaico135, this is what we have  😃, if we refresh the page, data will not be saved  

![Capture](https://user-images.githubusercontent.com/57408419/233594728-350e9ef0-4166-438b-9e44-0bce728a7792.PNG)

2023-04-21 10:30 UTC, merged